# Generated by Django 3.2.15 on 2025-02-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place_coords', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='correct_address',
            field=models.BooleanField(default=True, verbose_name='корректность адреса'),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='Долгота'),
        ),
    ]
