# Generated by Django 3.2.15 on 2025-01-27 13:55

from django.db import migrations


def update_existing_order_prices(apps,schema):
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')
    order_items = OrderItem.objects.all().select_related('product')
    for order_item in order_items.iterator():
        order_item.price = order_item.product.price
        order_item.save()

def move_backwards(apps, schema):
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')
    OrderItem.objects.all().update(price=0)

class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_orderitem_price'),
    ]

    operations = [
        migrations.RunPython(update_existing_order_prices,move_backwards)
    ]
