# Generated by Django 3.2.15 on 2025-01-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_auto_20250127_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CR', 'Создан'), ('AS', 'Собирается'), ('DE', 'Доставляется'), ('DO', 'Завершен')], db_index=True, default='CR', max_length=2, verbose_name='статус'),
        ),
    ]
