# Generated by Django 3.2.15 on 2025-01-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_auto_20250129_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Наличные'), ('ELEC', 'Электронно')], db_index=True, default='CASH', max_length=4, verbose_name='способ оплаты'),
            preserve_default=False,
        ),
    ]
